In [1]:
import numpy as np
import h5py
import pandas as pd

In [2]:
data = {}
targets = {}
files = open('files', 'r')
lines = files.readlines()
count = {}
for line in lines:
    fileName, target = line.strip().split(";")
    with h5py.File(fileName, 'r') as f:
        for k, v in f.items():
            tmp=np.array(v).transpose()
            if not target in data.keys():
                data[target]=tmp
                count[target] = tmp.shape[0]
            else:
                data[target] = np.concatenate((data[target], tmp))
                count[target]+= tmp.shape[0]
totalCount = 0
i=0
targetsColumn = None
for k, v in count.items():
    targets[k]=np.ones(v, dtype=int)*int(i)
    totalCount += v
    if i==0:
        targetsColumn = targets[k]
    else:
        targetsColumn = np.concatenate((targetsColumn, targets[k]))
    i += 1
targetsColumn=targetsColumn.reshape(targetsColumn.shape[0], 1)
dataSet = None
for k, v in data.items():
    if dataSet is None:
        dataSet = data[k]
    else:
        dataSet = np.concatenate((dataSet, data[k]))
dataSet = np.concatenate((dataSet, targetsColumn), axis=1)
dataSet

array([[ 1.08560000e+04,  9.76100000e+03,  8.76700000e+03, ...,
        -7.51399763e+01,  6.09741644e-01,  0.00000000e+00],
       [ 1.08830000e+04,  9.76700000e+03,  8.84500000e+03, ...,
        -7.51422682e+01,  6.14219984e-01,  0.00000000e+00],
       [ 1.08930000e+04,  9.78700000e+03,  8.79700000e+03, ...,
        -7.53548611e+01,  6.35108898e-01,  0.00000000e+00],
       ...,
       [ 1.00260000e+04,  9.28500000e+03,  9.51400000e+03, ...,
        -7.63544622e+01,  3.29000039e+00,  2.00000000e+00],
       [ 1.00040000e+04,  9.28100000e+03,  9.45100000e+03, ...,
        -7.64378927e+01,  3.29802285e+00,  2.00000000e+00],
       [ 9.87500000e+03,  8.97300000e+03,  8.63700000e+03, ...,
        -7.64516734e+01,  3.30682076e+00,  2.00000000e+00]])

In [3]:
df = pd.DataFrame(data=dataSet, columns=["Costal", "Blue", "Green", "Red", "NIR", "SWIR1", "SWIR2", "Longitude", "Latitude", "Target"])
df['Target'] = df['Target'].replace({0:"coca", 1:"nubes", 2:"cana"})
df

Costal    Blue   Green     Red      NIR    SWIR1   SWIR2  Longitude  \
0      10856.0  9761.0  8767.0  7646.0  17400.0  11280.0  7453.0 -75.139976   
1      10883.0  9767.0  8845.0  7616.0  17759.0  10465.0  7143.0 -75.142268   
2      10893.0  9787.0  8797.0  7574.0  17908.0  10563.0  7026.0 -75.354861   
3      10844.0  9813.0  8808.0  7617.0  17533.0  10779.0  7173.0 -75.130945   
4      10945.0  9848.0  9001.0  7699.0  21179.0  12428.0  7952.0 -75.300805   
...        ...     ...     ...     ...      ...      ...     ...        ...   
44076  10053.0  9231.0  8983.0  8140.0  21430.0  13972.0  9350.0 -76.357971   
44077   9465.0  8638.0  8662.0  8334.0  21553.0  12664.0  7129.0 -76.355002   
44078  10026.0  9285.0  9514.0  8931.0  21104.0  14579.0  8932.0 -76.354462   
44079  10004.0  9281.0  9451.0  8706.0  23822.0  16861.0  9970.0 -76.437893   
44080   9875.0  8973.0  8637.0  7995.0  15796.0  12962.0  8935.0 -76.451673   

       Latitude Target  
0      0.609742   coca  
1      0.614220   coca  
2      0.635109   coca  
3      0.639055   coca  
4      0.660083   coca  
...         ...    ...  
44076  3.289182   cana  
44077  3.289864   cana  
44078  3.290000   cana  
44079  3.298023   cana  
44080  3.306821   cana  

[44081 rows x 10 columns]

In [5]:
#Shuffle dataset mix
df = df.sample(frac=1).reset_index(drop=True)
df

Costal     Blue    Green      Red      NIR    SWIR1    SWIR2  \
0      34910.0  34590.0  33117.0  33679.0  36330.0  22978.0  20158.0   
1       9788.0   8890.0   7971.0   7583.0  10538.0   9671.0   7593.0   
2       9359.0   8381.0   8551.0   6402.0  21673.0   9802.0   6359.0   
3      47814.0  47364.0  45640.0  46585.0  46453.0  12685.0  14661.0   
4      40298.0  40209.0  37711.0  38312.0  39510.0  15815.0  14439.0   
...        ...      ...      ...      ...      ...      ...      ...   
44076   9461.0   8486.0   7990.0   6819.0  15139.0   9856.0   7024.0   
44077  10374.0   9694.0   9786.0   9565.0  16268.0  15310.0  10483.0   
44078  52779.0  52341.0  50002.0  51036.0  50320.0  13871.0  16307.0   
44079  10283.0   9244.0   8370.0   7269.0  18033.0  10816.0   7245.0   
44080  10927.0   9807.0   8760.0   7636.0  16757.0  10921.0   7268.0   

       Longitude  Latitude Target  
0       1.000000  1.000000  nubes  
1     -76.425970  3.169703   cana  
2     -76.326272  3.203482   cana  
3       1.000000  1.000000  nubes  
4       1.000000  1.000000  nubes  
...          ...       ...    ...  
44076 -76.233449  3.237652   cana  
44077 -76.446788  3.193957   cana  
44078   1.000000  1.000000  nubes  
44079 -72.074399  1.980925   coca  
44080 -74.504344  0.760217   coca  

[44081 rows x 10 columns]

In [6]:
#Creating the sub sets : Training set 70%, Test set 20%, Validation set 10%

In [7]:
from sklearn.model_selection import train_test_split

features = ["Costal", "Blue", "Green", "Red", "NIR", "SWIR1", "SWIR2"]
labels = ["coca", "cana", "nubes"]

X=df.loc[:, features]
y=df.loc[:, "Target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=109)


In [8]:
#Fitting parameters and validating it with validation set
from sklearn import svm

vdf = df.sample(frac=0.1).reset_index(drop=True)

X_v = vdf.loc[:, features]
y_v = vdf.loc[:, "Target"]

X_v_train, X_v_test, y_v_train, y_v_test = train_test_split(X_v, y_v, test_size=0.3, random_state=109)

classifier = svm.SVC(kernel='linear')
classifier.fit(X_v_train, y_v_train)

y_v_pred = classifier.predict(X_v_test)

In [9]:
from sklearn import metrics
metrics.confusion_matrix(y_v_test, y_v_pred, labels)

array([[485,  12,   2],
       [ 15, 477,   0],
       [  0,   0, 332]])

In [10]:
XX=vdf.loc[:, features]
yy=classifier.predict(XX)

In [11]:
from sklearn import metrics
print(metrics.confusion_matrix(y_v, yy, labels))
print(metrics.precision_recall_fscore_support(y_v, yy))

[[1577   51    2]
 [  42 1645    0]
 [   0    0 1091]]
(array([0.96992925, 0.97405806, 0.99817017]), array([0.97510373, 0.96748466, 1.        ]), array([0.97250961, 0.97076023, 0.99908425]), array([1687, 1630, 1091]))


In [12]:
from sklearn import metrics
print("Accuracy: ", metrics.accuracy_score(y_v_test, y_v_pred))
#The classifier works fine on validation set, now it's time to training over all the data set and
#Check if results are the same

Accuracy:  0.9780801209372638


In [13]:
X_train

Costal     Blue    Green      Red      NIR    SWIR1    SWIR2
6887   10741.0  10136.0   9842.0  10433.0  18134.0  21583.0  15278.0
25562   9690.0   8614.0   7854.0   6655.0  18794.0  11612.0   7393.0
2877   10008.0   9113.0   8599.0   7964.0  16958.0  13377.0   9642.0
745     9696.0   8735.0   8207.0   7117.0  18632.0  10286.0   6993.0
28769  12007.0  11640.0  11596.0  12115.0  21755.0  14140.0  11670.0
...        ...      ...      ...      ...      ...      ...      ...
18831  11210.0  10174.0   9391.0   8359.0  16029.0  14700.0  10780.0
16368  10415.0   9439.0   8452.0   7399.0  16617.0  10448.0   7145.0
16525  13206.0  12414.0  11469.0  11242.0  18128.0  13520.0  10621.0
7925   10167.0   9549.0   9456.0   9936.0  15882.0  17529.0  12581.0
19701  45180.0  44585.0  42831.0  43533.0  44162.0  12547.0  14115.0

[30856 rows x 7 columns]

In [14]:
#Clasificador para los datos inmensos
classifier = svm.SVC(kernel='linear')
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [15]:
#Prediction and metrics of the classifier predicts to the entire test set
y_pred = classifier.predict(X_test)

print("Accuracy: ", metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.9787523629489603


In [19]:
big_pred = classifier.predict(X)
print("Accyracy Big Prediction:", metrics.accuracy_score(y, big_pred))
print("Confusion Matrix:\n", metrics.confusion_matrix(y, big_pred, labels))

Accyracy Big Prediction: 0.979288128672217
Confusion Matrix:
 [[16074   481     0]
 [  404 16570     4]
 [    6    18 10524]]


In [25]:
metadata_df = df
metadata_df['Prediction']=big_pred
metadata_df

Costal     Blue    Green      Red      NIR    SWIR1    SWIR2  \
0      34910.0  34590.0  33117.0  33679.0  36330.0  22978.0  20158.0   
1       9788.0   8890.0   7971.0   7583.0  10538.0   9671.0   7593.0   
2       9359.0   8381.0   8551.0   6402.0  21673.0   9802.0   6359.0   
3      47814.0  47364.0  45640.0  46585.0  46453.0  12685.0  14661.0   
4      40298.0  40209.0  37711.0  38312.0  39510.0  15815.0  14439.0   
...        ...      ...      ...      ...      ...      ...      ...   
44076   9461.0   8486.0   7990.0   6819.0  15139.0   9856.0   7024.0   
44077  10374.0   9694.0   9786.0   9565.0  16268.0  15310.0  10483.0   
44078  52779.0  52341.0  50002.0  51036.0  50320.0  13871.0  16307.0   
44079  10283.0   9244.0   8370.0   7269.0  18033.0  10816.0   7245.0   
44080  10927.0   9807.0   8760.0   7636.0  16757.0  10921.0   7268.0   

       Longitude  Latitude Target Prediction  
0       1.000000  1.000000  nubes      nubes  
1     -76.425970  3.169703   cana       cana  
2     -76.326272  3.203482   cana       cana  
3       1.000000  1.000000  nubes      nubes  
4       1.000000  1.000000  nubes      nubes  
...          ...       ...    ...        ...  
44076 -76.233449  3.237652   cana       cana  
44077 -76.446788  3.193957   cana       cana  
44078   1.000000  1.000000  nubes      nubes  
44079 -72.074399  1.980925   coca       coca  
44080 -74.504344  0.760217   coca       coca  

[44081 rows x 11 columns]

In [31]:
#Buscando los datos de coca encontrados correctamente con SVM
targetCoca = metadata_df['Target'] == 'coca'
predictionCoca = metadata_df['Prediction'] == 'coca'
cocaOK = metadata_df[targetCoca & predictionCoca]
cocaOK.to_csv('./csv/cocaOK.csv', encoding='utf-8', index=False)
cocaOK.to_csv('./csv/back/cocaOK.csv', encoding='utf-8')
cocaOK

Costal     Blue    Green     Red      NIR    SWIR1    SWIR2  \
8      11468.0  10342.0   9507.0  8199.0  20353.0  12591.0   8179.0   
9      10564.0   9567.0   8879.0  7661.0  18215.0  11251.0   7528.0   
10     12433.0  11394.0  10160.0  9486.0  13225.0  13292.0  11238.0   
12     11788.0  10691.0   9704.0  8419.0  19182.0  11840.0   7916.0   
20     10600.0   9577.0   8662.0  7811.0  17761.0  13312.0   8913.0   
...        ...      ...      ...     ...      ...      ...      ...   
44066  12065.0  11195.0   9965.0  9094.0  15759.0  10414.0   7908.0   
44069  10191.0   9074.0   8453.0  6984.0  27576.0  15073.0   8703.0   
44071  11365.0  10445.0   9892.0  9209.0  18077.0  17448.0  11878.0   
44079  10283.0   9244.0   8370.0  7269.0  18033.0  10816.0   7245.0   
44080  10927.0   9807.0   8760.0  7636.0  16757.0  10921.0   7268.0   

       Longitude  Latitude Target Prediction  
8     -75.462221  1.088219   coca       coca  
9     -72.406751  2.073126   coca       coca  
10    -76.200261  0.437431   coca       coca  
12    -76.028005  0.368392   coca       coca  
20    -75.890534  1.485837   coca       coca  
...          ...       ...    ...        ...  
44066 -71.571854  2.144273   coca       coca  
44069 -72.429017  2.215512   coca       coca  
44071 -75.783435  0.845663   coca       coca  
44079 -72.074399  1.980925   coca       coca  
44080 -74.504344  0.760217   coca       coca  

[16074 rows x 11 columns]

In [32]:
#Buscando los datos de coca encontrados incorrectamente con SVM
targetCoca = metadata_df['Target'] == 'coca'
predictionCoca = metadata_df['Prediction'] != 'coca'
cocaFail = metadata_df[targetCoca & predictionCoca]
cocaFail.to_csv('./csv/cocaFail.csv', encoding='utf-8', index=False)
cocaFail.to_csv('./csv/back/cocaFail.csv', encoding='utf-8')
cocaFail

Costal     Blue    Green      Red      NIR    SWIR1    SWIR2  \
7      10049.0   9111.0   8296.0   7250.0  17677.0  10564.0   7300.0   
92     24781.0  24598.0  25584.0  26007.0  31058.0  30979.0  26150.0   
109     9416.0   8417.0   7763.0   6630.0  18515.0  10398.0   6785.0   
238    10284.0   9386.0   8724.0   7961.0  15603.0  10934.0   7759.0   
379    10059.0   9083.0   8520.0   7324.0  19746.0  11279.0   7408.0   
...        ...      ...      ...      ...      ...      ...      ...   
43603  10578.0   9707.0   9139.0   8173.0  20731.0  12427.0   8150.0   
43680   9861.0   9104.0   9596.0   9037.0  23814.0  16297.0  10367.0   
43754   9046.0   8098.0   7242.0   5915.0  21875.0  13808.0   9149.0   
43957   9689.0   8862.0   8505.0   9002.0  16917.0  19377.0  12705.0   
44003  11020.0  10285.0   9752.0   9719.0  16184.0  16287.0  10934.0   

       Longitude  Latitude Target Prediction  
7     -72.120092  1.417174   coca       cana  
92    -75.924660  1.521646   coca       cana  
109   -71.862841  1.133091   coca       cana  
238   -72.516202  1.438787   coca       cana  
379   -71.944417  1.571163   coca       cana  
...          ...       ...    ...        ...  
43603 -72.237084  2.164875   coca       cana  
43680 -72.405062  2.196490   coca       cana  
43754 -72.423656  1.857733   coca       cana  
43957 -71.992028  1.190284   coca       cana  
44003 -72.473487  2.136413   coca       cana  

[481 rows x 11 columns]

In [33]:
#Buscando los datos de caña encontrados correctamente con SVM
targetCana = metadata_df['Target'] == 'cana'
predictionCana = metadata_df['Prediction'] == 'cana'
canaOK = metadata_df[targetCana & predictionCana]
canaOK.to_csv('./csv/canaOK.csv', encoding='utf-8', index=False)
canaOK.to_csv('./csv/back/canaOK.csv', encoding='utf-8')
canaOK

Costal     Blue    Green      Red      NIR    SWIR1    SWIR2  \
1       9788.0   8890.0   7971.0   7583.0  10538.0   9671.0   7593.0   
2       9359.0   8381.0   8551.0   6402.0  21673.0   9802.0   6359.0   
5      10365.0   9527.0   8939.0   8898.0  13518.0  13216.0   9765.0   
14      9635.0   8609.0   8035.0   6836.0  17903.0   9732.0   6432.0   
15      9901.0   9051.0   8921.0   9427.0  22209.0  16516.0  10172.0   
...        ...      ...      ...      ...      ...      ...      ...   
44072  10048.0   9150.0   8348.0   7571.0  14690.0   9838.0   7020.0   
44074  11623.0  11007.0  10646.0  11265.0  20587.0  17973.0  12543.0   
44075  11392.0  10649.0  10018.0   9751.0  12715.0  12715.0  10086.0   
44076   9461.0   8486.0   7990.0   6819.0  15139.0   9856.0   7024.0   
44077  10374.0   9694.0   9786.0   9565.0  16268.0  15310.0  10483.0   

       Longitude  Latitude Target Prediction  
1     -76.425970  3.169703   cana       cana  
2     -76.326272  3.203482   cana       cana  
5     -76.416935  3.175006   cana       cana  
14    -76.477423  3.192557   cana       cana  
15    -76.308243  3.248683   cana       cana  
...          ...       ...    ...        ...  
44072 -76.307020  3.135400   cana       cana  
44074 -76.366363  3.102492   cana       cana  
44075 -76.392581  3.130405   cana       cana  
44076 -76.233449  3.237652   cana       cana  
44077 -76.446788  3.193957   cana       cana  

[16570 rows x 11 columns]

In [35]:
#Buscando los datos de caña encontrados incorrectamente con SVM
targetCana = metadata_df['Target'] == 'cana'
predictionCana = metadata_df['Prediction'] != 'cana'
canaFail = metadata_df[targetCana & predictionCana]
canaFail.to_csv('./csv/canaFail.csv', encoding='utf-8', index=False)
canaFail.to_csv('./csv/back/canaFail.csv', encoding='utf-8', index=False)
canaFail

Costal     Blue    Green      Red      NIR    SWIR1    SWIR2  \
6      10973.0   9971.0   8968.0   8055.0  15020.0   9644.0   7596.0   
91      9901.0   8926.0   8244.0   7392.0  18891.0  12651.0   8294.0   
116    11405.0  10415.0   9413.0   8441.0  15668.0   9893.0   7776.0   
290     9774.0   8786.0   8441.0   6969.0  21623.0  12344.0   7751.0   
543     9934.0   8972.0   8653.0   7600.0  17943.0  14229.0   9529.0   
...        ...      ...      ...      ...      ...      ...      ...   
43598  11884.0  10601.0  10753.0   9237.0  17035.0   8541.0   5565.0   
43654  12618.0  11869.0  11466.0  10401.0  23804.0  16418.0  10816.0   
43786   9950.0   8919.0   8341.0   7288.0  18358.0  11903.0   7717.0   
43830   9741.0   8687.0   8055.0   6859.0  17642.0   9583.0   6528.0   
43958  17342.0  16742.0  15445.0  15569.0  21234.0  15379.0  12383.0   

       Longitude  Latitude Target Prediction  
6     -76.404366  3.060522   cana       coca  
91    -76.441217  3.263288   cana       coca  
116   -76.403423  3.062151   cana       coca  
290   -76.414338  3.249896   cana       coca  
543   -76.390376  3.095542   cana       coca  
...          ...       ...    ...        ...  
43598 -76.352011  3.171837   cana       coca  
43654 -76.367857  3.109817   cana       coca  
43786 -76.420025  3.165234   cana       coca  
43830 -76.420954  3.153159   cana       coca  
43958 -76.431230  3.067405   cana       coca  

[408 rows x 11 columns]